<!doctype html>
<html lang="zh-Cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>账务系统后台管理</title>
    <link rel="stylesheet" href="{{ mix('css/all.css') }}">
</head>

<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
</style>
<body>
    <div id="app">

    </div>
</body>

<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/admin.js') }}"></script>

</html>
